apiVersion: v1
kind: Secret
metadata:
  name: gestion-produits-secrets
type: Opaque
data:
  DB_USER: cHJvZHVpdHNfdXNlcg==        
  DB_PASS: cHJvZHVpdHNfcGFzcw==        
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3MxMjM= 
