apiVersion: v1
kind: Service
metadata:
  name: gestion-produits-service
spec:
  type: NodePort
  selector:
    app: gestion-produits
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
